services:
  - type: web
    name: saptmarkets-backend
    env: node
    rootDir: backend
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        value: your_mongodb_atlas_uri
      - key: JWT_SECRET
        value: your_jwt_secret_key
      - key: JWT_SECRET_FOR_VERIFY
        value: your_verify_secret
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5055 